// src/routes/header.svelte
<header>
  <div style="text-align: center;">
    <p></p>
    <h1><b>Zack Polson</b></h1>
    <a href="./">Home</a> |
    <a href="./">Blog</a> |
    <a href="./">Play</a> |
    <a href="./">About</a> |
    <a href="./">Contact</a> |
    <a href="./">Toggle Dark Mode</a>
    <p></p>
  </div>
  <hr />
</header>

// app/components/Header.tsx
const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Blog", href: "/" },
  { label: "Play", href: "/" },
  { label: "About", href: "/" },
  { label: "Contact", href: "/" },
];

export default function Header() {
  return (
    <header>
      <div style={{ textAlign: "center" }}>
        <h1>
          <b>Zack Polson</b>
        </h1>
        <nav>
          {NAV_LINKS.map((link, i) => (
            <span key={link.label}>
              <a href={link.href}>{link.label}</a>
              {i < NAV_LINKS.length - 1 && " | "}
            </span>
          ))}
        </nav>
        <p />
      </div>
      <hr />
    </header>
  );
}
